/**
 * Page definitions — single source of truth for all scenarios.
 *
 * Each entry becomes a BackstopJS scenario. To add a page, just append
 * another object. Per-page overrides (delay, selectors, etc.) are merged
 * into the scenario defaults defined in backstop.config.js.
 */
module.exports = [
  {"label":"Home","path":"/","tags":["esiv2"]},
  {"label":"About","path":"/about","tags":["esiv2","about"]},
  {"label":"About - Vision Strategy","path":"/about/vision-strategy","tags":["esiv2","about"]},
  {"label":"About - Commitment Quality","path":"/about/commitment-quality","tags":["esiv2","about"]},
  {"label":"About - Our History","path":"/about/our-history","tags":["esiv2","about"]},
  {"label":"About - Commitment Quality - Certificates","path":"/about/commitment-quality/certificates","tags":["esiv2","about"]},
  {"label":"About - Commitment Quality - Six Sigma","path":"/about/commitment-quality/six-sigma","tags":["esiv2","about"]},
  {"label":"Our Businesses","path":"/our-businesses","tags":["esiv2","business"]},
  {"label":"Our Businesses - Electronics","path":"/our-businesses/electronics","tags":["esiv2","business"]},
  {"label":"Our Businesses - Industrial Specialty","path":"/our-businesses/industrial-specialty","tags":["esiv2","business"]},
  {"label":"Key Markets","path":"/key-markets","tags":["esiv2","market"]},
  {"label":"Key Markets - Automotive","path":"/key-markets/automotive","tags":["esiv2","market"]},
  {"label":"Key Markets - Computing Telecom","path":"/key-markets/computing-telecom","tags":["esiv2","market"]},
  {"label":"Key Markets - Construction Machinery","path":"/key-markets/construction-machinery","tags":["esiv2","market"]},
  {"label":"Key Markets - Consumer Electronics","path":"/key-markets/consumer-electronics","tags":["esiv2","market"]},
  {"label":"Key Markets - Consumer Goods","path":"/key-markets/consumer-goods","tags":["esiv2","market"]},
  {"label":"Key Markets - Energy Resources","path":"/key-markets/energy-resources","tags":["esiv2","market"]},
  {"label":"Key Markets - Medical","path":"/key-markets/medical","tags":["esiv2","market"]},
  {"label":"Key Markets - Military Aerospace","path":"/key-markets/military-aerospace","tags":["esiv2","market"]},
  {"label":"Key Markets - Mobile Wearables","path":"/key-markets/mobile-wearables","tags":["esiv2","market"]},
  {"label":"News Media","path":"/news-media","tags":["esiv2","news"]},
  {"label":"News Media - Business News","path":"/news-media/business-news","tags":["esiv2","news"]},
  {"label":"News Media - Contacts","path":"/news-media/contacts","tags":["esiv2","news"]},
  {"label":"Sustainability","path":"/sustainability","tags":["esiv2","sustainability"]},
  {"label":"Sustainability - CEO Message","path":"/sustainability/ceo-message","tags":["esiv2","sustainability"]},
  {"label":"Sustainability - Vision Strategy","path":"/sustainability/vision-strategy","tags":["esiv2","sustainability"]},
  {"label":"Sustainability - Sustainable Chemistry","path":"/sustainability/sustainable-chemistry","tags":["esiv2","sustainability"]},
  {"label":"Sustainability - Environmental Stewardship","path":"/sustainability/environmental-stewardship","tags":["esiv2","sustainability"]},
  {"label":"Sustainability - Social Impact","path":"/sustainability/social-impact","tags":["esiv2","sustainability"]},
  {"label":"Sustainability - Governance Compliance","path":"/sustainability/governance-compliance","tags":["esiv2","sustainability"]},
  {"label":"Sustainability - Resources","path":"/sustainability/resources","tags":["esiv2","sustainability"]},
  {"label":"Sustainability - Resources - Policies","path":"/sustainability/resources/policies","tags":["esiv2","sustainability"]},
  {"label":"Sustainability - Environmental Stewardship - Energy and Emissions","path":"/sustainability/environmental-stewardship/energy-and-emissions","tags":["esiv2","sustainability"]},
  {"label":"Sustainability - Environmental Stewardship - Environmental Compliance","path":"/sustainability/environmental-stewardship/environmental-compliance","tags":["esiv2","sustainability"]},
  {"label":"Sustainability - Environmental Stewardship - Water Waste","path":"/sustainability/environmental-stewardship/water-waste","tags":["esiv2","sustainability"]},
  {"label":"Sustainability - Social Impact - Occupational Health Safety","path":"/sustainability/social-impact/occupational-health-safety","tags":["esiv2","sustainability"]},
  {"label":"Sustainability - Social Impact - Workforce Prosperity","path":"/sustainability/social-impact/workforce-prosperity","tags":["esiv2","sustainability"]},
  {"label":"Sustainability - Social Impact - Volunteering Charitable Giving","path":"/sustainability/social-impact/volunteering-charitable-giving","tags":["esiv2","sustainability"]},
  {"label":"Sustainability - Governance Compliance - Ethics Compliance","path":"/sustainability/governance-compliance/ethics-compliance","tags":["esiv2","sustainability"]},
  {"label":"Sustainability - Governance and Compliance - Sustainable Supply Chain","path":"/sustainability/governance-and-compliance/sustainable-supply-chain","tags":["esiv2","sustainability"]},
  {"label":"Sustainability - Governance Compliance - Data Security Privacy","path":"/sustainability/governance-compliance/data-security-privacy","tags":["esiv2","sustainability"]},
  {"label":"Terms Conditions","path":"/terms-conditions","tags":["esiv2","other"]},
  {"label":"Sitemap","path":"/sitemap","tags":["esiv2","other"]},
  {"label":"Contact Us","path":"/contact-us","tags":["esiv2","other"]},
  {"label":"Careers","path":"/careers","tags":["esiv2","other"]},
  {"label":"Website Privacy Policy","path":"/website-privacy-policy","tags":["esiv2","other"]},
  {"label":"California Transparency Act","path":"/california-transparency-act","tags":["esiv2","other"]},
  {"label":"UK Modern Slavery Act","path":"/uk-modern-slavery-act","tags":["esiv2","other"]},
  {"label":"Federal Transparency Coverage Rule","path":"/federal-transparency-coverage-rule","tags":["esiv2","other"]},
];
